version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: travelhub-postgres
    restart: always
    environment:
      POSTGRES_DB: transport_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5323:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - travelhub-network

  redis:
    image: redis:7-alpine
    container_name: travelhub-redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - travelhub-network

volumes:
  postgres_data:

networks:
  travelhub-network:
    driver: bridge
