spring:
  application:
    name: transport-booking-system
  main:
    allow-circular-references: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
logging:
  level:
    com.naren.backend: INFO
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.flyway: INFO

# JWT Configuration
jwt:
  secret: mySecretKeyForTravelHubBackend2024
  expiration: 86400 # 24 hours in seconds
  refresh-token:
    expiration: 604800 # 7 days in seconds